spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/movie
    username: root
    password: system
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      data-source-properties:
        characterEncoding: UTF-8
        useUnicode: "true"
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: none
server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
