spring:
  profiles:
    active: dev
    groups:
      dev: local, localdb
      test: test, testdb
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      data-source-properties:
        characterEncoding: UTF-8
        useUnicode: "true"
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: none
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      data-source-properties:
        characterEncoding: UTF-8
        useUnicode: "true"
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: create
---
server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
# api:
#   secret: av_jqTlPjr
#   id: Hqsz1tECcg712EE903wl

# 운영 장비에서는 create, create-drop, update 사용하면 안됌.
# 개발 초기 단계는 create 또는 update
# 테스트 서버는 update 또는 validate
# 스테이징과 운영 서버는 validate 또는 none
